config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "activity_logs/index"
  end
  namespace :student do
    resources:trainings, only: [:index, :show]
  end
  namespace :admin do
    resources :activity_logs, only: [:index]
    resources :trainings
    resources :uebungs
  end
  namespace :coach do
    resources :trainings
    resources :uebungs
  end
  devise_for :benutzers



  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  root "home#index"
  # get "home/index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_benutzer!
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1 class="text-center mb-4">Home</h1>
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Choose your option</h2>
      <div class="button-group mt-4">
        <% if current_benutzer.admin? %>
          <%= link_to 'Activity Log', '/admin/activity_logs', class: 'btn btn-info' %>
          <%= link_to 'Manage Trainings', admin_trainings_path, class: 'btn btn-primary' %>
          <%= link_to 'Manage Uebungs', admin_uebungs_path, class: 'btn btn-primary' %>

        <% elsif current_benutzer.coach? %>
          <%= link_to 'View My Trainings', '/coach/trainings', class: 'btn btn-info' %>
          <%= link_to 'View My Übungen', '/coach/uebungs', class: 'btn btn-warning' %>
        <% elsif current_benutzer.student? %>
          <%= link_to 'View Existing Trainings and Übungen', '/student/trainings', class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="mt-4">
        <%= button_to 'Logout', destroy_benutzer_session_path, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>