config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "activity_logs/index"
  end
  namespace :student do
    resources:trainings, only: [:index, :show]
  end
  namespace :admin do
    resources :activity_logs, only: [:index]
    resources :trainings
    resources :uebungs
  end
  namespace :coach do
    resources :trainings
    resources :uebungs
  end
  devise_for :benutzers



  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  root "home#index"
  # get "home/index"
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :benutzer
  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/admin/trainings_controller.rb
module Admin
  class TrainingsController < ApplicationController
    before_action :authenticate_benutzer!
    before_action :authorize_admin!
    before_action :set_training, only: %i[show edit update destroy]

    def index
      @trainings = Training.all  # Fetch all trainings for admin
    end

    def show
    end

    def new
      @training = Training.new
    end

    def create
      @training = Training.new(training_params)
      if @training.save
        current_benutzer.log_activity("Training Created", "Title: #{@training.title}")  
        Rails.logger.info "Neues Training wurde erstellt"
        redirect_to admin_trainings_path, notice: 'Training was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @training.update(training_params)
        current_benutzer.log_activity("Training Updated", "Title: #{@training.title}")
        Rails.logger.info "Training wurde aktualisiert"
        redirect_to admin_trainings_path, notice: 'Training was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      current_benutzer.log_activity("Training Deleted", "Title: #{@training.title}")
      @training.destroy
      Rails.logger.info "Training wurde gelöscht"
      redirect_to admin_trainings_path, notice: 'Training was successfully destroyed.'
    end

    private

    def authorize_admin!
      redirect_to root_path, alert: "You are not authorized to access this page." unless current_benutzer.admin?
    end

    def set_training
      @training = Training.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.info "Training nicht gefunden"
      redirect_to admin_trainings_path, alert: 'Training not found.'
    end

    def training_params
      params.require(:training).permit(:title, :description)
    end
  end
end

app/controllers/coach/trainings_controller.rb
module Coach
  class TrainingsController < ApplicationController
    before_action :authenticate_benutzer!
    before_action :require_coach 
    before_action :set_training, only: %i[show edit update destroy]

    def index
      @trainings = current_benutzer.trainings
    end

    def show
    end

    def new
      @training = current_benutzer.trainings.build
    end

    def create
      @training = current_benutzer.trainings.build(training_params)
      if @training.save
        current_benutzer.log_activity("Training Created", "Title: #{@training.title}")  # Log the activity
        Rails.logger.info "Neues Training wurde erstellt"
        redirect_to coach_trainings_path, notice: 'Training was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @training.update(training_params)
        current_benutzer.log_activity("Training Updated", "Title: #{@training.title}")  # Log the activity
        Rails.logger.info "Training wurde aktualisiert"
        redirect_to coach_trainings_path, notice: 'Training was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      current_benutzer.log_activity("Training Deleted", "Title: #{@training.title}")  # Log the activity
      @training.destroy
      Rails.logger.info "Training wurde gelöscht"
      redirect_to coach_trainings_path, notice: 'Training was successfully destroyed.'
    end

    private

    def require_coach
      unless current_benutzer.coach? || current_benutzer.admin?
        Rails.logger.info "Sie haben keinen Zugriff"
        redirect_to root_path, alert: 'Access Denied.'
      end
    end

    def set_training
      @training = current_benutzer.trainings.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.info "Training nicht gefunden"
      redirect_to coach_trainings_path, alert: 'Training not found.'
    end

    def training_params
      params.require(:training).permit(:title, :description)
    end
  end
end

app/controllers/student/trainings_controller.rb
module Student
  class TrainingsController < ApplicationController
    before_action :authenticate_benutzer!
    before_action :require_student

    def index
      @trainings = Training.all
    end

    def show
      @training = Training.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.info "Training nicht gefunden"
      redirect_to student_trainings_path, alert: 'Training not found.'
    end

    private

    def require_student
      unless current_benutzer.student?
        Rails.logger.info "Sie haben keinen Zugriff"
        redirect_to root_path, alert: 'Access Denied.'
      end
    end
  end
end

app/helpers/coach/trainings_helper.rb
module Coach::TrainingsHelper
end

app/helpers/student/trainings_helper.rb
module Student::TrainingsHelper
end

app/views/admin/trainings/_form.html.erb
<%= form_with(model: training, url: training.new_record? ? admin_trainings_path : admin_training_path(training), local: true) do |form| %>
    <% if training.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>
        <ul>
          <% training.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  

app/views/admin/trainings/edit.html.erb
<div class="container">
  <h1>Edit Training</h1>

  <%= render "form", training: @training %>

  <div class="mt-4">
    <%= link_to "Show this training", admin_training_path(@training), class: 'btn btn-info' %>
    <%= link_to "Back to Trainings", admin_trainings_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/trainings/index.html.erb
<div class="container">
  <h1>Manage All Trainings</h1>
  <div class="text-center mb-4">
    <%= link_to "Back to Home", root_path, class: "btn btn-primary btn-lg" %>
    <%= link_to 'New Training', new_admin_training_path, class: 'btn btn-primary btn-lg' %>
  </div>

  <div class="table-container">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @trainings.each do |training| %>
          <tr>
            <td><%= training.title %></td>
            <td><%= truncate(training.description, length: 100) %></td>
            <td><%= link_to 'Show', admin_training_path(training), class: 'btn btn-info' %></td>
            <td><%= link_to 'Edit', edit_admin_training_path(training), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', admin_training_path(training), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>